# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'docker/**/*'
    - 'Rakefile'
    - 'setup.rb'
    - 'spec/**/*'
    - 'app/**/*'
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
